export const routes = {
  home: "/",
  login: "/dang-nhap",
  register: "/dang-ky",
  forgotPassword: "/quen-mat-khau",
  gameRoom: "/phong/:roomId",
  history: "/lich-su",
  profile: "/ho-so",
  friends: "/ban-be",
  settings: "/cai-dat",
  canonicalLogin: "/login",
  canonicalRegister: "/register",
  canonicalForgotPassword: "/forgot-password",
  canonicalHome: "/home",
  queue: "/queue",
  canonicalGameRoom: "/room/:roomId",
  canonicalGame: "/game/:roomId",
  canonicalHistory: "/history",
  matchHistory: "/history/:matchId",
  canonicalProfile: "/profile/:username",
  canonicalFriends: "/friends",
  canonicalSettings: "/settings",
  guest: "/guest",
  guestPlay: "/guest/play",
  ai: "/ai",
  offline: "/offline",
  spectator: "/spectate/:roomId",
} as const;
