import { useCallback, useEffect, useRef, useState, type FormEvent } from "react";
import { useNavigate } from "react-router-dom";
import type { CreateRoomRequest, RoomDetail, RoomSummary } from "@ottv2/contracts";
import { routes } from "../../app/routes";
import { Button, LoadingState, Modal, UiGlyph, useToast } from "../ui";
import { createRoom, getRooms, joinRoom, subscribeToRooms } from "../../services/rooms/roomApi";
import { ApiError } from "../../services/http/apiError";

type RoomCardData = RoomSummary | RoomDetail;
const timerLabels: Record<number, string> = { 30: "30 giây", 60: "1 phút", 300: "5 phút", 600: "10 phút", 1800: "30 phút", 3600: "60 phút" };

function RoomCard({ room, onJoin, onCopy, onSpectate }: { room: RoomCardData; onJoin: (room: RoomCardData) => void; onCopy: (roomId: string) => void; onSpectate: (room: RoomCardData) => void }) {
  return <article className="room-card"><div className="room-card-head"><span className={`room-status ${room.status.toLowerCase()}`}>{room.status === "WAITING" ? "ĐANG CHỜ" : room.status}</span><span className="room-visibility">{room.visibility === "PRIVATE" ? <><UiGlyph name="lock" size={13} /> Private</> : "Public"}</span></div><h3>{room.name}</h3><div className="room-id-row"><p className="room-id">#{room.roomId}</p><button className="icon-button copy-room-button" type="button" aria-label={`Sao chép mã phòng ${room.roomId}`} onClick={() => onCopy(room.roomId)}><UiGlyph name="copy" size={16} /></button></div><div className="room-card-meta"><span><UiGlyph name="players" size={14} /> {room.players}/{room.playerCapacity}</span><span><UiGlyph name="clock" size={14} /> {timerLabels[room.timerSeconds]}</span><span>{room.mode}</span></div><div className="room-card-actions"><Button className="room-join-button" variant="secondary" onClick={() => onJoin(room)} disabled={room.status !== "WAITING" || room.players >= room.playerCapacity}>{room.players >= room.playerCapacity ? "Đã đủ người" : "Tham gia"}</Button>{room.spectatorsEnabled && room.players > 0 && <Button className="room-spectate-button" variant="ghost" onClick={() => onSpectate(room)}>Xem trận</Button>}</div></article>;
}

export function RoomBrowser({ openCreateOnMount = false }: { openCreateOnMount?: boolean }) {
  const navigate = useNavigate(); const { notify } = useToast();
  const [rooms, setRooms] = useState<RoomCardData[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [roomEvent, setRoomEvent] = useState(""); const previousRooms = useRef<RoomCardData[] | null>(null); const [query, setQuery] = useState(""); const [searchResult, setSearchResult] = useState<RoomCardData>(); const [createOpen, setCreateOpen] = useState(openCreateOnMount); const [joinTarget, setJoinTarget] = useState<RoomCardData>(); const [joinPassword, setJoinPassword] = useState(""); const [joinError, setJoinError] = useState(""); const [pending, setPending] = useState(false);
  const [form, setForm] = useState<CreateRoomRequest>({ name: "", visibility: "PUBLIC", timerSeconds: 300, spectatorsEnabled: false, spectatorCapacity: undefined });

  const loadRooms = useCallback((showSpinner = true) => { if (showSpinner) setLoading(true); setError(""); getRooms().then((result) => { const nextRooms = result.rooms; const previous = previousRooms.current; if (previous !== null) { const previousById = new Map(previous.map((room) => [room.roomId, room])); const nextById = new Map(nextRooms.map((room) => [room.roomId, room])); const created = nextRooms.some((room) => !previousById.has(room.roomId)); const removed = previous.some((room) => !nextById.has(room.roomId)); const updated = nextRooms.some((room) => previousById.has(room.roomId) && JSON.stringify(previousById.get(room.roomId)) !== JSON.stringify(room)); setRoomEvent(created ? "ROOM_CREATED · Danh sách đã cập nhật" : removed ? "ROOM_REMOVED · Danh sách đã cập nhật" : updated ? "ROOM_UPDATED · Danh sách đã cập nhật" : ""); } previousRooms.current = nextRooms; setRooms(nextRooms); }).catch((reason) => setError(reason instanceof ApiError ? reason.message : "Không thể tải danh sách phòng.")).finally(() => { if (showSpinner) setLoading(false); }); }, []);
  useEffect(() => {
    let fallback: number | undefined;
    const receive = (nextRooms: RoomCardData[]) => {
      const previous = previousRooms.current;
      if (previous !== null) {
        const previousById = new Map(previous.map((room) => [room.roomId, room]));
        const nextById = new Map(nextRooms.map((room) => [room.roomId, room]));
        const created = nextRooms.some((room) => !previousById.has(room.roomId));
        const removed = previous.some((room) => !nextById.has(room.roomId));
        const updated = nextRooms.some((room) => previousById.has(room.roomId) && JSON.stringify(previousById.get(room.roomId)) !== JSON.stringify(room));
        setRoomEvent(created ? "Có phòng mới." : removed ? "Danh sách phòng đã cập nhật." : updated ? "Thông tin phòng đã cập nhật." : "");
      }
      previousRooms.current = nextRooms; setRooms(nextRooms); setLoading(false); setError("");
    };
    loadRooms();
    const unsubscribe = subscribeToRooms(receive, () => {
      setRoomEvent("Kết nối danh sách phòng bị gián đoạn; đang dùng đồng bộ dự phòng.");
      if (fallback === undefined) fallback = window.setInterval(() => loadRooms(false), 30000);
    });
    return () => { unsubscribe(); if (fallback !== undefined) window.clearInterval(fallback); };
  }, [loadRooms]);
  useEffect(() => { if (openCreateOnMount) setCreateOpen(true); }, [openCreateOnMount]);

  const showAuthError = (reason: unknown) => { if (reason instanceof ApiError && reason.status === 401) { notify("Bạn cần đăng nhập để tạo hoặc tham gia phòng.", "warning"); navigate(routes.login); return; } notify(reason instanceof ApiError ? reason.message : "Thao tác phòng đấu thất bại.", "error"); };
  const copyRoomId = async (roomId: string) => { await navigator.clipboard?.writeText(roomId); notify(`Đã sao chép mã phòng ${roomId}.`, "success"); };
  const submitSearch = async (event: FormEvent) => { event.preventDefault(); if (!query.trim()) { setSearchResult(undefined); return; } setPending(true); try { const result = await getRooms(query); setSearchResult(result.rooms[0]); if (!result.rooms[0]) notify("Phòng đấu không tồn tại", "warning"); } catch (reason) { setSearchResult(undefined); notify(reason instanceof ApiError ? reason.message : "Phòng đấu không tồn tại", "warning"); } finally { setPending(false); } };
  const openSpectator = (room: RoomCardData) => navigate(`/spectate/${encodeURIComponent(room.roomId)}`);
  const submitCreate = async (event: FormEvent) => { event.preventDefault(); setPending(true); try { const result = await createRoom({ ...form, ...(form.visibility === "PUBLIC" ? { password: undefined } : {}) }, crypto.randomUUID()); setCreateOpen(false); notify(`Đã tạo phòng ${result.room.roomId}.`, "success"); navigate(`/game/${encodeURIComponent(result.room.roomId)}`); } catch (reason) { showAuthError(reason); } finally { setPending(false); } };
  const submitJoin = async (event: FormEvent) => { event.preventDefault(); if (!joinTarget) return; setPending(true); setJoinError(""); try { const result = await joinRoom(joinTarget.roomId, joinTarget.visibility === "PRIVATE" ? { password: joinPassword } : {}, crypto.randomUUID()); setJoinTarget(undefined); setJoinPassword(""); notify("Đã vào phòng đấu.", "success"); navigate(`/game/${encodeURIComponent(result.room.roomId)}`); } catch (reason) { if (reason instanceof ApiError && reason.status === 401 && joinTarget.visibility === "PRIVATE") setJoinError("Mật khẩu phòng không đúng."); else showAuthError(reason); } finally { setPending(false); } };

  return <section className="rooms-section" id="rooms"><div className="rooms-toolbar"><div><p className="eyebrow">PHÒNG ĐẤU</p><h2>Phòng đang mở</h2><p className="rooms-subtitle">Chọn một phòng Public hoặc tạo không gian riêng cho trận Unranked. Danh sách cập nhật trực tiếp.</p></div><div className="room-toolbar-actions"><form className="room-search" onSubmit={submitSearch}><label className="visually-hidden" htmlFor="room-search-input">Tìm Room ID</label><input id="room-search-input" value={query} onChange={(event) => setQuery(event.target.value.toUpperCase())} placeholder="Nhập id phòng chơi" maxLength={6} /><Button type="submit" variant="secondary" pending={pending}>Tìm</Button></form><Button type="button" onClick={() => setCreateOpen(true)}>Tạo phòng</Button></div></div>{roomEvent && <p className="rooms-live" role="status" aria-live="polite">{roomEvent}</p>}{searchResult && <div className="search-result"><span className="eyebrow">KẾT QUẢ TÌM KIẾM</span><RoomCard room={searchResult} onJoin={setJoinTarget} onCopy={copyRoomId} onSpectate={openSpectator} /></div>}{loading ? <LoadingState label="Đang tải phòng đấu…" /> : error ? <div className="rooms-empty"><strong>Không thể tải phòng</strong><p>{error}</p><Button variant="secondary" onClick={() => loadRooms()}>Thử lại</Button></div> : rooms.length === 0 ? <div className="rooms-empty"><UiGlyph name="empty" size={26} /><strong>Chưa có phòng Public nào</strong><p>Hãy là người đầu tiên mở một trận Unranked.</p><Button type="button" onClick={() => setCreateOpen(true)}>Tạo phòng đầu tiên</Button></div> : <div className="room-grid-scroll"><div className="room-grid">{rooms.map((room) => <RoomCard key={room.roomId} room={room} onJoin={setJoinTarget} onCopy={copyRoomId} onSpectate={openSpectator} />)}</div></div>}
    <Modal open={createOpen} title="Tạo phòng đấu" description="Phòng custom luôn là Unranked. Room ID sẽ được máy chủ sinh tự động." onClose={() => setCreateOpen(false)}><form className="form-stack" onSubmit={submitCreate}><label>Tên phòng <span className="field-hint">tuỳ chọn, tối đa 30 ký tự</span><input value={form.name ?? ""} onChange={(event) => setForm((current) => ({ ...current, name: event.target.value }))} maxLength={30} placeholder="Ví dụ: Đêm đấu xanh đỏ" /></label><fieldset className="choice-fieldset"><legend>Quyền truy cập</legend><label className="check-row"><input type="radio" checked={form.visibility === "PUBLIC"} onChange={() => setForm((current) => ({ ...current, visibility: "PUBLIC", password: undefined }))} /> Public — xuất hiện trong danh sách</label><label className="check-row"><input type="radio" checked={form.visibility === "PRIVATE"} onChange={() => setForm((current) => ({ ...current, visibility: "PRIVATE" }))} /> Private — cần mật khẩu</label></fieldset>{form.visibility === "PRIVATE" && <label>Mật khẩu phòng<input value={form.password ?? ""} onChange={(event) => setForm((current) => ({ ...current, password: event.target.value }))} minLength={1} maxLength={12} required /></label>}<label>Thời gian mỗi bên<select value={form.timerSeconds} onChange={(event) => setForm((current) => ({ ...current, timerSeconds: Number(event.target.value) as 30 | 60 | 300 | 600 | 1800 | 3600 }))}>{Object.entries(timerLabels).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label><label className="check-row"><input type="checkbox" checked={form.spectatorsEnabled} onChange={(event) => setForm((current) => ({ ...current, spectatorsEnabled: event.target.checked, spectatorCapacity: event.target.checked ? 10 : undefined }))} /> Cho phép spectator</label>{form.spectatorsEnabled && <label>Sức chứa spectator<select value={form.spectatorCapacity ?? 10} onChange={(event) => setForm((current) => ({ ...current, spectatorCapacity: Number(event.target.value) as 1 | 2 | 5 | 10 | 50 | 100 }))}>{[1, 2, 5, 10, 50, 100].map((value) => <option value={value} key={value}>{value} người</option>)}</select></label>}<div className="modal-actions"><Button type="button" variant="secondary" onClick={() => setCreateOpen(false)}>Huỷ</Button><Button type="submit" pending={pending} pendingLabel="Đang tạo…">Tạo phòng</Button></div></form></Modal>
    <Modal open={Boolean(joinTarget)} title="Tham gia phòng" description={joinTarget ? `${joinTarget.name} · #${joinTarget.roomId}` : undefined} onClose={() => { setJoinTarget(undefined); setJoinPassword(""); setJoinError(""); }}><form className="form-stack" onSubmit={submitJoin}>{joinTarget?.visibility === "PRIVATE" && <label>Mật khẩu phòng<input autoFocus value={joinPassword} onChange={(event) => { setJoinPassword(event.target.value); setJoinError(""); }} maxLength={12} required /></label>}{joinTarget?.visibility === "PUBLIC" && <p className="form-hint">Đây là phòng Public. Bạn có thể vào ngay nếu còn chỗ.</p>}{joinError && <p className="form-error" role="alert">{joinError}</p>}<div className="modal-actions"><Button type="button" variant="secondary" onClick={() => { setJoinTarget(undefined); setJoinError(""); }}>Huỷ</Button><Button type="submit" pending={pending}>Tham gia</Button></div></form></Modal>
  </section>;
}
